name: sccess-id-secrets

on:
  push:
# Define at least one job that runs on ubuntu-latest:
jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Printing Repository Secret
      run: echo "The secret is \${{ secrets.SECRET }}"
